services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - taskit
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/Taskit.Web/Dockerfile
    ports:
      - '5152:5152'
    environment:
      ASPNETCORE_URLS: http://+:5152
      ConnectionStrings__DefaultConnection: 'Data Source=/app/taskit.db'
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    volumes:
      - ./src/Taskit.Web/taskit.db:/app/taskit.db
    depends_on:
      rabbitmq:
        condition: service_healthy
      worker:
        condition: service_started
      aiworker:
        condition: service_started
    networks:
      - taskit

  worker:
    build:
      context: .
      dockerfile: src/Taskit.Notification.Worker/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: 'Data Source=/app/taskit.db'
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
    volumes:
      - ./src/Taskit.Web/taskit.db:/app/taskit.db
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - taskit

  aiworker:
    build:
      context: .
      dockerfile: src/Taskit.AI.Orchestrator/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: 'Data Source=/app/taskit.db'
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      OpenAI__ApiKey: "${OpenAI__ApiKey:-}"
    volumes:
      - ./src/Taskit.Web/taskit.db:/app/taskit.db
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - taskit

networks:
  taskit:
    driver: bridge
